# Generated by Django 4.1.2 on 2022-10-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date',
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.article'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.client'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='prixUnitaire',
            field=models.FloatField(default=0, verbose_name='Prix unitaire'),
        ),
    ]
