# Generated by Django 4.1.2 on 2022-10-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0003_panier_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date',
        ),
    ]
