# Generated by Django 4.1.2 on 2022-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0004_remove_panier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
