# Generated by Django 4.1.3 on 2022-11-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0007_alter_article_description_alter_article_intitule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneachat',
            name='panier',
        ),
    ]
