# Generated by Django 4.1.3 on 2022-11-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0008_remove_ligneachat_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneachat',
            name='panier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='achat.panier'),
        ),
    ]
