# Generated by Django 4.1.3 on 2022-11-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0010_alter_ligneachat_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneachat',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.article'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.client'),
        ),
    ]
