# Generated by Django 4.1.3 on 2022-11-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0011_alter_ligneachat_article_alter_panier_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=18, null=True, verbose_name='Telephone'),
        ),
    ]
