# Generated by Django 4.1.3 on 2022-11-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0013_alter_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneachat',
            name='panier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='achat.panier'),
        ),
    ]
